### ISSUE TITLE
Fix standard Jas

### ISSUE THREAD

**Issue by Shidouuu** [Shidouuu/svosmapi#5]
```bash
[12:09:29 ERROR Seasonal Villager Outfits SMAPI ver.] Mod crashed when loading asset 'Characters/Jas'. SMAPI will use the default asset instead. Error details:
SContentLoadException: Failed loading asset 'assets/Characters/Jas/Jas_Spring_Outdoor_Sun' from SMAPI\shidouuu.svosmapi: the specified path doesn't exist.
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.ThrowLoadError(IAssetName assetName, ContentLoadErrorType errorType, String reasonPhrase, Exception exception) in SMAPI\Framework\ContentManagers\ModContentManager.cs:line 360
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.LoadExact[T](IAssetName assetName, Boolean useCache) in SMAPI\Framework\ContentManagers\ModContentManager.cs:line 123
   at StardewModdingAPI.Framework.ModHelpers.ModContentHelper.Load[T](String relativePath) in SMAPI\Framework\ModHelpers\ModContentHelper.cs:line 57
   at StardewModdingAPI.Events.AssetRequestedEventArgs.<>c__DisplayClass18_0`1.<LoadFromModFile>b__0(IAssetInfo _) in SMAPI\Events\AssetRequestedEventArgs.cs:line 109
   at StardewModdingAPI.Framework.ContentManagers.GameContentManager.ApplyLoader[T](IAssetInfo info, List`1 loadOperations) in SMAPI\Framework\ContentManagers\GameContentManager.cs:line 175
```

**Comment by Shidouuu** [comment]
Fixed in 499f9bd13a5d0f4b3003213448d16f65acb52327 and c7a7f9e1d18170ed59ef3f00f4f740c1c64fa597.
